name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.13.4
  get: ^4.6.6
  camera: ^0.11.1
  video_player: ^2.9.2
  image: ^4.5.3
  ffi: ^2.1.3

flutter:
  uses-material-design: true
